stages:
  - build
  - test

build:
  stage: build
  image: archlinux:base-devel
  script:
    - make clean
    - make -j $(nproc)
  artifacts:
    paths:
      - bin/quickbuild

test:
  stage: test
  image: archlinux:base-devel
  script:
    - ./bin/quickbuild test
    - ./bin/quickbuild
  dependencies:
    - build
