stages:
  - build
  - test

build:
  stage: build
  image: archlinux:base-devel
  script:
    - make clean
    - make -j $(nproc)
  artifacts:
    paths:
      - bin/qvickbuild

test:
  stage: test
  image: archlinux:base-devel
  script:
    - ./bin/qvickbuild
    - ./bin/qvickbuild test
  dependencies:
    - build
