stages:
  - build
  - test

build:
  image: gcc
  script:
    - make clean
    - make
  artifacts:
    paths:
      - bin/quickbuild

test:
  image: gcc
  script:
    - ./bin/quickbuild
    - ./bin/quickbuild --configfile tests/test1
  dependencies:
    - build
