build-job:
  image: gcc
  script:
    - make clean
    - make
  artifacts:
    paths:
      - bin/quickbuild

test-job:
  image: gcc
  script:
    - ./bin/quickbuild --configfile tests/test1
    - ./bin/quickbuild
  dependencies:
    - build-job
